# Generated by Django 4.2 on 2023-06-07 05:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, verbose_name='氏名')),
                ('kana_characters', models.CharField(blank=True, max_length=50, verbose_name='カタカナ')),
                ('nickname', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('school_classification', models.CharField(max_length=10, verbose_name='学校区分')),
                ('school_name', models.CharField(max_length=15, verbose_name='学校名')),
                ('Department', models.CharField(max_length=10, verbose_name='学科')),
                ('student_number', models.CharField(max_length=10, verbose_name='学籍番号')),
                ('grade', models.CharField(blank=True, max_length=1, verbose_name='学年')),
                ('introduction', models.CharField(blank=True, max_length=75, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('followers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
