FROM python:3.10.0
ENV PYTHONUNBUFFERED 1 
RUN pip install django==4.2.0
RUN pip install numpy
RUN pip install pandas
RUN pip install matplotlib
RUN pip install Pillow
RUN pip install django social-auth-app-django